### ISSUE TITLE
Dialog not sized correctly on some screens

### ISSUE THREAD

**Issue by brake4bots** [brake4bots/WinSetView#3]
The initial release only displayed properly on machines where the display scaling was set to 100%. On machines set to larger values, such as 125%, the dialog was too small, causing buttons to become inaccessible. I updated the code to detect scaling and adjust the dialog appropriately and changed the dialog to resizable just in case it's still incorrect. This fix introduced a new bug that caused incorrect display on some machines that were at 100%. That was caused by a negative number in the DpiValue entry on some computers. This has now been accounted for in the latest code. The dialog should now open up at an appropriate size on all monitors. Please contact me if it's not displaying correctly on your computer.

**Comment by brake4bots** [comment]
Fixed as noted above.

**Comment by LesFerch** [comment]
WinSetView v2 should display properly regardless of resolution or screen scaling. Please let me know if you have any issues with it not displaying correctly.
